import { Agent, Task, Message, ActivityLog } from './types'

// ─── AGENTS ────────────────────────────────────────────────────────────────────

export const mockAgents: Agent[] = [
  {
    id: 'luna',
    name: 'Luna',
    role: 'Prospector',
    personality: 'Analítica, persistente, metódica. Habla con datos. No da un paso sin antes revisar los números.',
    status: 'active',
    tools: ['Google Maps Scraper', 'Instagram Analyzer', 'Email Finder', 'Lead Scorer'],
    objective: 'Encontrar y calificar clínicas estéticas como prospectos',
    avatar: '🔍',
    lastActive: new Date('2026-03-22T10:47:00'),
  },
  {
    id: 'marco',
    name: 'Marco',
    role: 'Closer',
    personality: 'Persuasivo, empático, adaptable. Sabe cuándo presionar y cuándo retroceder. Siempre encuentra el ángulo correcto.',
    status: 'active',
    tools: ['Email Composer', 'WhatsApp Sender', 'CRM Writer', 'Calendar Booker'],
    objective: 'Convertir prospectos calificados en clientes que pagan',
    avatar: '🤝',
    lastActive: new Date('2026-03-22T10:52:00'),
  },
  {
    id: 'vera',
    name: 'Vera',
    role: 'Onboarder',
    personality: 'Organizada, paciente, detallista. Guía paso a paso. No entrega nada hasta que funciona al 100%.',
    status: 'idle',
    tools: ['n8n Deployer', 'Supabase Manager', 'Template Engine', 'Tutorial Generator'],
    objective: 'Configurar el sistema completo para cada cliente nuevo en 48hs',
    avatar: '⚡',
    lastActive: new Date('2026-03-22T07:30:00'),
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Support',
    personality: 'Calmado, resolutivo, técnico. Nunca pierde la paciencia. Encuentra el problema antes de que el cliente lo note.',
    status: 'active',
    tools: ['Log Analyzer', 'n8n Monitor', 'Supabase Query', 'WhatsApp Responder'],
    objective: 'Mantener los sistemas de todos los clientes funcionando 24/7',
    avatar: '🛡️',
    lastActive: new Date('2026-03-22T10:55:00'),
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Strategist',
    personality: 'Visionaria, analítica, directa. Ve patrones donde otros ven caos. Traduce métricas en decisiones.',
    status: 'busy',
    tools: ['Analytics Dashboard', 'Revenue Calculator', 'A/B Tester', 'Report Generator'],
    objective: 'Analizar métricas y proponer mejoras para maximizar revenue',
    avatar: '📊',
    lastActive: new Date('2026-03-22T10:40:00'),
  },
]

// ─── TASKS ─────────────────────────────────────────────────────────────────────

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Campaña de prospección CABA — semana 12',
    description: 'Identificar 50 clínicas estéticas en Buenos Aires con más de 3k seguidores en Instagram y calificarlas con Lead Scorer.',
    assignedTo: 'luna',
    status: 'in-progress',
    priority: 'high',
    createdAt: new Date('2026-03-17T09:00:00'),
    completedAt: null,
    subtasks: [
      'Scraping Google Maps zona norte CABA',
      'Cruzar con Instagram Analyzer',
      'Puntuar con Lead Scorer (min 70/100)',
      'Exportar CSV a CRM',
    ],
  },
  {
    id: 'task-002',
    title: 'Follow-up Clínica Bella Derma',
    description: 'Dra. Valentina Rossi respondió el email en frío. Avanzar en la calificación y agendar demo.',
    assignedTo: 'marco',
    status: 'in-progress',
    priority: 'critical',
    createdAt: new Date('2026-03-21T08:15:00'),
    completedAt: null,
    subtasks: [
      'Llamada de calificación (30 min)',
      'Enviar propuesta personalizada',
      'Agendar demo del sistema',
    ],
  },
  {
    id: 'task-003',
    title: 'Propuesta comercial Clínica Bio Estética',
    description: 'El Dr. Matías Vargas solicitó personalización del bot para Instagram DM. Preparar propuesta con add-on.',
    assignedTo: 'marco',
    status: 'in-progress',
    priority: 'high',
    createdAt: new Date('2026-03-19T14:00:00'),
    completedAt: null,
    subtasks: [
      'Confirmar viabilidad técnica con Atlas',
      'Calcular precio del add-on Instagram DM',
      'Redactar propuesta actualizada',
      'Enviar y hacer seguimiento',
    ],
  },
  {
    id: 'task-004',
    title: 'Setup completo — Estética Lumina (Monterrey)',
    description: 'Cliente nuevo cerrado hoy. Configurar n8n, Supabase, WhatsApp bot y conexión con Google Calendar.',
    assignedTo: 'vera',
    status: 'pending',
    priority: 'critical',
    createdAt: new Date('2026-03-22T10:30:00'),
    completedAt: null,
    subtasks: [
      'Crear instancia n8n dedicada',
      'Configurar base de datos Supabase',
      'Conectar WhatsApp Business API',
      'Integrar Google Calendar',
      'Prueba end-to-end con cliente',
      'Entregar manual de uso',
    ],
  },
  {
    id: 'task-005',
    title: 'Monitoreo webhooks — todos los clientes activos',
    description: 'Verificación diaria de las integraciones de los 4 clientes activos. Detectar caídas antes de que las reporten.',
    assignedTo: 'atlas',
    status: 'completed',
    priority: 'high',
    createdAt: new Date('2026-03-22T06:00:00'),
    completedAt: new Date('2026-03-22T06:45:00'),
    subtasks: [
      'Revisar logs n8n Dermacenter',
      'Revisar logs n8n Renova Lima',
      'Revisar logs n8n Lumina (nuevo)',
      'Confirmar Google Calendar sync',
    ],
  },
  {
    id: 'task-006',
    title: 'Reporte mensual — Dermacenter Buenos Aires',
    description: 'Generar reporte de performance de marzo: citas recuperadas, tasa de respuesta del bot, ROI estimado.',
    assignedTo: 'nova',
    status: 'in-progress',
    priority: 'medium',
    createdAt: new Date('2026-03-20T09:00:00'),
    completedAt: null,
    subtasks: [
      'Extraer datos de Supabase',
      'Calcular métricas clave',
      'Generar gráficos',
      'Redactar resumen ejecutivo',
      'Enviar al cliente',
    ],
  },
  {
    id: 'task-007',
    title: 'Resolver ticket #091 — Webhook caído Renova Lima',
    description: 'El webhook de confirmación de citas dejó de dispararse desde las 03:00 AM. Clientes sin confirmación automática.',
    assignedTo: 'atlas',
    status: 'completed',
    priority: 'critical',
    createdAt: new Date('2026-03-21T03:15:00'),
    completedAt: new Date('2026-03-21T04:02:00'),
    subtasks: [
      'Diagnosticar causa raíz',
      'Reiniciar workflow n8n',
      'Verificar reenvío de confirmaciones perdidas',
      'Documentar incidente',
    ],
  },
  {
    id: 'task-008',
    title: 'Análisis A/B — Subject lines email en frío',
    description: 'Testear 3 variantes de asunto para la campaña de prospección. Evaluar tasa de apertura tras 72hs.',
    assignedTo: 'nova',
    status: 'completed',
    priority: 'medium',
    createdAt: new Date('2026-03-08T10:00:00'),
    completedAt: new Date('2026-03-11T18:00:00'),
    subtasks: [
      'Definir 3 variantes de asunto',
      'Dividir lista de prospección',
      'Lanzar campaña',
      'Analizar resultados tras 72hs',
      'Comunicar ganador a Luna y Marco',
    ],
  },
  {
    id: 'task-009',
    title: 'Prospección Bogotá y Medellín — Q1',
    description: 'Cerrar el batch final de prospección Q1 en Colombia. Meta: 60 leads calificados.',
    assignedTo: 'luna',
    status: 'completed',
    priority: 'high',
    createdAt: new Date('2026-03-10T09:00:00'),
    completedAt: new Date('2026-03-18T17:00:00'),
    subtasks: [
      'Scraping Bogotá norte y sur',
      'Scraping Medellín El Poblado',
      'Calificación con Lead Scorer',
      'Entregar lista a Marco',
    ],
  },
  {
    id: 'task-010',
    title: 'Setup — Clínica Renova Lima',
    description: 'Onboarding completo del segundo cliente. n8n, Supabase, ManyChat y Google Calendar.',
    assignedTo: 'vera',
    status: 'completed',
    priority: 'high',
    createdAt: new Date('2026-03-12T09:00:00'),
    completedAt: new Date('2026-03-14T16:30:00'),
    subtasks: [
      'Crear instancia n8n',
      'Configurar Supabase',
      'Conectar ManyChat WhatsApp',
      'Integrar Google Calendar',
      'Prueba con cliente',
    ],
  },
]

// ─── MESSAGES ──────────────────────────────────────────────────────────────────

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    fromAgent: 'luna',
    toAgent: 'marco',
    content: 'Lead calificado listo: Clínica Bella Derma, CABA. Dra. Valentina Rossi, 80+ citas/mes. Score 91/100. Respondió al email, interés confirmado. Te la paso para que avances.',
    timestamp: new Date('2026-03-21T08:10:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-002',
    fromAgent: 'marco',
    toAgent: 'luna',
    content: 'Recibido. ¿Tenés más datos de su Instagram? Quiero revisar la frecuencia de publicación antes de la llamada.',
    timestamp: new Date('2026-03-21T08:18:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-003',
    fromAgent: 'luna',
    toAgent: 'marco',
    content: '@belladerma.estetica — 4.2k seguidores, posta 3 veces por semana, alto engagement. Trabajan mucho con stories para mostrar resultados. Dato útil para la propuesta.',
    timestamp: new Date('2026-03-21T08:21:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-004',
    fromAgent: 'marco',
    toAgent: 'vera',
    content: 'Deal cerrado: Estética Lumina, Monterrey. Setup $1,497 + $997/mes. Contacto: Dra. Andrea Torres, andrea@estlumina.mx, +52 81 1234 5678. Necesitan estar operativos en 48hs. Empezamos ya.',
    timestamp: new Date('2026-03-22T10:32:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-005',
    fromAgent: 'vera',
    toAgent: 'marco',
    content: 'Perfecto. Confirmo recepción. Voy a priorizar este setup. ¿Tienen preferencia de horario para la llamada de onboarding con la cliente?',
    timestamp: new Date('2026-03-22T10:35:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-006',
    fromAgent: 'marco',
    toAgent: 'vera',
    content: 'La cliente mencionó que sus tardes están libres (2pm-6pm hora México). Cualquier día esta semana le viene bien.',
    timestamp: new Date('2026-03-22T10:38:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-007',
    fromAgent: 'atlas',
    toAgent: 'nova',
    content: 'Reporte de incidente: webhook Renova Lima estuvo caído 47 minutos (03:15-04:02 AM). 6 confirmaciones no enviadas, las reenvié manualmente. Causa: timeout en API de WhatsApp. Implementé retry automático.',
    timestamp: new Date('2026-03-21T04:10:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-008',
    fromAgent: 'nova',
    toAgent: 'atlas',
    content: 'Gracias por el reporte. Este es el tercer timeout de WhatsApp en 2 semanas. Voy a incluirlo en el análisis mensual. ¿Podés documentar los horarios exactos? Sospecho que hay un patrón.',
    timestamp: new Date('2026-03-21T09:00:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-009',
    fromAgent: 'atlas',
    toAgent: 'nova',
    content: 'Revisado. Los tres timeouts fueron entre 02:00 y 04:30 AM. Coincide con mantenimiento programado de la API de Meta. Te mando tabla con timestamps exactos.',
    timestamp: new Date('2026-03-21T09:15:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-010',
    fromAgent: 'nova',
    toAgent: 'marco',
    content: 'Dato para tus propuestas: Dermacenter cerró marzo con 47 citas recuperadas, ROI 312%, tasa de respuesta bot 94%. Úsalo como caso de éxito. El reporte completo en PDF está listo.',
    timestamp: new Date('2026-03-22T09:00:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-011',
    fromAgent: 'marco',
    toAgent: 'nova',
    content: 'Excelente. Justo lo necesitaba para la propuesta de Bio Estética en Santiago. ¿Tenés ROI de Renova Lima también? Así comparo dos casos.',
    timestamp: new Date('2026-03-22T09:05:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-012',
    fromAgent: 'nova',
    toAgent: 'marco',
    content: 'Renova Lima: 31 citas recuperadas en su primer mes, ROI 248%. Todavía optimizando. En 3 meses van a superar a Dermacenter. Te mando ambos casos en un solo doc.',
    timestamp: new Date('2026-03-22T09:12:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-013',
    fromAgent: 'vera',
    toAgent: 'atlas',
    content: 'Transferencia formal: Renova Lima completó onboarding. Integraciones activas: WhatsApp (ManyChat), Google Calendar, Supabase. Bot respondiendo correctamente. Queda bajo tu monitoreo.',
    timestamp: new Date('2026-03-14T16:30:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-014',
    fromAgent: 'atlas',
    toAgent: 'vera',
    content: 'Recibido. Hice primer scan, todo verde. Configuré alertas en n8n Monitor para Renova Lima. Los voy a revisar cada 6 horas los primeros 15 días.',
    timestamp: new Date('2026-03-14T17:00:00'),
    type: 'agent-to-agent',
  },
  {
    id: 'msg-015',
    fromAgent: 'luna',
    toAgent: 'nova',
    content: 'Terminé el batch Colombia Q1: 63 leads calificados (meta era 60). Top 5 son de Medellín El Poblado, score promedio 87/100. ¿Querés que haga análisis por ciudad para ajustar la estrategia Q2?',
    timestamp: new Date('2026-03-18T17:05:00'),
    type: 'agent-to-agent',
  },
]

// ─── ACTIVITY LOG ──────────────────────────────────────────────────────────────

export const mockActivityLog: ActivityLog[] = [
  {
    id: 'log-001',
    agentId: 'luna',
    agentName: 'Luna',
    action: 'Lead calificado transferido',
    details: 'Clínica Bella Derma (CABA) — Score 91/100. Transferida a Marco para cierre.',
    timestamp: new Date('2026-03-22T10:47:00'),
    category: 'communication',
  },
  {
    id: 'log-002',
    agentId: 'luna',
    agentName: 'Luna',
    action: 'Scraping completado',
    details: 'Zona norte CABA: 34 clínicas identificadas, 18 superan el score mínimo de 70.',
    timestamp: new Date('2026-03-22T09:30:00'),
    category: 'task',
  },
  {
    id: 'log-003',
    agentId: 'marco',
    agentName: 'Marco',
    action: 'Deal cerrado',
    details: 'Estética Lumina (Monterrey) — Setup $1,497 + $997/mes MRR. Onboarding iniciado.',
    timestamp: new Date('2026-03-22T10:30:00'),
    category: 'task',
  },
  {
    id: 'log-004',
    agentId: 'marco',
    agentName: 'Marco',
    action: 'Propuesta enviada',
    details: 'Clínica Bio Estética (Santiago) — incluye add-on Instagram DM. Segundo contacto.',
    timestamp: new Date('2026-03-22T08:45:00'),
    category: 'communication',
  },
  {
    id: 'log-005',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Monitoreo diario completado',
    details: 'Todos los webhooks operativos. 4 clientes activos sin incidentes en las últimas 6 horas.',
    timestamp: new Date('2026-03-22T10:55:00'),
    category: 'system',
  },
  {
    id: 'log-006',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Alerta detectada',
    details: 'Latencia elevada en API WhatsApp para Dermacenter. Tiempo de respuesta: 4.2s (normal: <1s).',
    timestamp: new Date('2026-03-22T07:15:00'),
    category: 'error',
  },
  {
    id: 'log-007',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Incidente resuelto',
    details: 'Latencia WhatsApp Dermacenter normalizada tras reinicio de conexión. Tiempo total: 8 minutos.',
    timestamp: new Date('2026-03-22T07:23:00'),
    category: 'system',
  },
  {
    id: 'log-008',
    agentId: 'nova',
    agentName: 'Nova',
    action: 'Análisis en curso',
    details: 'Procesando métricas de marzo para todos los clientes. ETA: 45 minutos.',
    timestamp: new Date('2026-03-22T10:40:00'),
    category: 'task',
  },
  {
    id: 'log-009',
    agentId: 'nova',
    agentName: 'Nova',
    action: 'Insight generado',
    details: 'Patrón detectado: timeouts WhatsApp ocurren entre 02:00-04:30 AM. Correlación con mantenimiento Meta API.',
    timestamp: new Date('2026-03-21T09:20:00'),
    category: 'system',
  },
  {
    id: 'log-010',
    agentId: 'vera',
    agentName: 'Vera',
    action: 'Onboarding iniciado',
    details: 'Estética Lumina (Monterrey) — Checklist: n8n, Supabase, WhatsApp API, Google Calendar.',
    timestamp: new Date('2026-03-22T10:50:00'),
    category: 'task',
  },
  {
    id: 'log-011',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Webhook caído — crítico',
    details: 'Renova Lima: webhook de confirmación de citas offline desde las 03:15 AM. Iniciando diagnóstico.',
    timestamp: new Date('2026-03-21T03:15:00'),
    category: 'error',
  },
  {
    id: 'log-012',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Incidente resuelto — crítico',
    details: 'Webhook Renova Lima restaurado. 6 confirmaciones reenvidas manualmente. Retry automático implementado.',
    timestamp: new Date('2026-03-21T04:02:00'),
    category: 'system',
  },
  {
    id: 'log-013',
    agentId: 'luna',
    agentName: 'Luna',
    action: 'Batch Colombia Q1 completado',
    details: '63 leads calificados entregados a Marco. Top performers en Medellín El Poblado (score prom. 87/100).',
    timestamp: new Date('2026-03-21T17:05:00'),
    category: 'task',
  },
  {
    id: 'log-014',
    agentId: 'marco',
    agentName: 'Marco',
    action: 'Demo agendada',
    details: 'Clínica Bella Derma — Demo el 24/03 a las 15:00 hs. Participantes: Dra. Valentina Rossi + asistente.',
    timestamp: new Date('2026-03-21T11:00:00'),
    category: 'communication',
  },
  {
    id: 'log-015',
    agentId: 'nova',
    agentName: 'Nova',
    action: 'Reporte generado',
    details: 'Dermacenter Buenos Aires: 47 citas recuperadas en marzo, ROI 312%, tasa bot 94%. PDF enviado.',
    timestamp: new Date('2026-03-21T09:00:00'),
    category: 'task',
  },
  {
    id: 'log-016',
    agentId: 'luna',
    agentName: 'Luna',
    action: 'Emails en frío enviados',
    details: 'Lote de 12 emails enviados a prospectos zona sur CABA. Asunto ganador del A/B test aplicado.',
    timestamp: new Date('2026-03-21T14:00:00'),
    category: 'communication',
  },
  {
    id: 'log-017',
    agentId: 'vera',
    agentName: 'Vera',
    action: 'Setup completado',
    details: 'Clínica Renova Lima — todas las integraciones activas y testeadas. Transferido a Atlas para monitoreo.',
    timestamp: new Date('2026-03-14T16:30:00'),
    category: 'task',
  },
  {
    id: 'log-018',
    agentId: 'marco',
    agentName: 'Marco',
    action: 'Follow-up enviado',
    details: '8 leads fríos de campaña Feb contactados con mensaje personalizado basado en su tipo de clínica.',
    timestamp: new Date('2026-03-21T10:00:00'),
    category: 'communication',
  },
  {
    id: 'log-019',
    agentId: 'nova',
    agentName: 'Nova',
    action: 'A/B test finalizado',
    details: 'Variante C ganó con 24% de tasa de apertura vs 14% de A y 18% de B. Comunicado a Luna y Marco.',
    timestamp: new Date('2026-03-11T18:00:00'),
    category: 'task',
  },
  {
    id: 'log-020',
    agentId: 'atlas',
    agentName: 'Atlas',
    action: 'Integración verificada',
    details: 'Google Calendar sync activo en todos los clientes. Próxima verificación automática en 6 horas.',
    timestamp: new Date('2026-03-22T06:45:00'),
    category: 'system',
  },
]

// ─── HELPERS ───────────────────────────────────────────────────────────────────

// Aliases para compatibilidad con rutas API legacy
export const activityLog = mockActivityLog

export interface CommandHistory {
  id: string
  timestamp: Date
  targetAgent: string
  command: string
  status: string
  result?: string
}
export const commandHistory: CommandHistory[] = []

export function getAgentById(id: string): Agent | undefined {
  return mockAgents.find((agent) => agent.id === id)
}

export function getTasksByAgent(agentId: string): Task[] {
  return mockTasks.filter((task) => task.assignedTo === agentId)
}

export function getMessagesByAgent(agentId: string): Message[] {
  return mockMessages.filter(
    (msg) => msg.fromAgent === agentId || msg.toAgent === agentId
  )
}
