import { Agent, ActivityEntry, Lead, Command, AgentMessage } from "./types";

export const agents: Agent[] = [
  {
    id: "outreach",
    name: "Outreach",
    emoji: "🎯",
    description: "Encuentra clínicas y envía emails en frío",
    status: "active",
    currentTask: "Buscando clínicas estéticas en Bogotá con Instagram activo",
    lastActionTime: "hace 2 min",
    metrics: {
      emailsEnviados: 47,
      tasaRespuesta: "18%",
      prospectosTotales: 134,
      prospectoHoy: 12,
    },
  },
  {
    id: "ventas",
    name: "Ventas",
    emoji: "🤝",
    description: "Califica leads y cierra deals",
    status: "working",
    currentTask: "Siguiendo up con Clínica Bella Derma — esperando respuesta",
    lastActionTime: "hace 8 min",
    metrics: {
      leadsCalificados: 23,
      dealsCerrados: 3,
      tasaConversion: "13%",
      pipeline: "$12,450 USD",
    },
  },
  {
    id: "onboarding",
    name: "Onboarding",
    emoji: "⚙️",
    description: "Configura el sistema para nuevos clientes",
    status: "idle",
    currentTask: null,
    lastActionTime: "hace 3 horas",
    metrics: {
      clientesOnboarded: 3,
      tiempoPromedioSetup: "4.2 días",
      tareasCompletadas: 18,
      pendientes: 2,
    },
  },
  {
    id: "web-builder",
    name: "Web Builder",
    emoji: "🌐",
    description: "Crea sitios web para clientes",
    status: "working",
    currentTask: "Construyendo landing page para Estética Lumina (Monterrey)",
    lastActionTime: "hace 15 min",
    metrics: {
      sitiosConstruidos: 2,
      enProgreso: 1,
      tiempoPromedioEntrega: "3.5 días",
      satisfaccionCliente: "9.2/10",
    },
  },
  {
    id: "reportes",
    name: "Reportes",
    emoji: "📊",
    description: "Métricas y estado de clientes",
    status: "idle",
    currentTask: null,
    lastActionTime: "hace 1 hora",
    metrics: {
      reportesGenerados: 8,
      clientesActivos: 3,
      citasRecuperadas: 47,
      ingresosMes: "$2,991 USD",
    },
  },
  {
    id: "soporte",
    name: "Soporte",
    emoji: "🛠️",
    description: "Soporte técnico y resolución de problemas",
    status: "active",
    currentTask: "Revisando integración de WhatsApp para Dermacenter Buenos Aires",
    lastActionTime: "hace 5 min",
    metrics: {
      ticketsResueltos: 12,
      tiempoRespuestaPromedio: "28 min",
      satisfaccion: "96%",
      ticketsAbiertos: 1,
    },
  },
];

export const activityLog: ActivityEntry[] = [
  {
    id: "act-001",
    timestamp: "2026-03-20T21:58:00Z",
    agentId: "outreach",
    agentName: "Outreach",
    agentEmoji: "🎯",
    type: "action",
    description: "Envió email en frío a Clínica Estética Nova (Medellín) — asunto: '¿Perdiendo citas por no responder a tiempo?'",
    linkedTask: "Campaña Bogotá-Medellín Q1",
  },
  {
    id: "act-002",
    timestamp: "2026-03-20T21:50:00Z",
    agentId: "outreach",
    agentName: "Outreach",
    agentEmoji: "🎯",
    type: "message",
    description: "Lead calificado transferido: Clínica Bella Derma (CABA) respondió al email — interés confirmado",
    linkedTask: "Lead calificado",
    toAgentId: "ventas",
    toAgentName: "Ventas",
    toAgentEmoji: "🤝",
  },
  {
    id: "act-003",
    timestamp: "2026-03-20T21:45:00Z",
    agentId: "ventas",
    agentName: "Ventas",
    agentEmoji: "🤝",
    type: "task",
    description: "Recibió lead de Outreach: Clínica Bella Derma — iniciando proceso de calificación",
    linkedTask: "Calificación Bella Derma",
  },
  {
    id: "act-004",
    timestamp: "2026-03-20T21:30:00Z",
    agentId: "soporte",
    agentName: "Soporte",
    agentEmoji: "🛠️",
    type: "action",
    description: "Resolvió problema de integración con Google Calendar para Dermacenter Buenos Aires — webhook reconfigurado",
    linkedTask: "Ticket #089 - Dermacenter",
  },
  {
    id: "act-005",
    timestamp: "2026-03-20T21:15:00Z",
    agentId: "web-builder",
    agentName: "Web Builder",
    agentEmoji: "🌐",
    type: "task",
    description: "Completó sección hero y formulario de reservas para landing de Estética Lumina (Monterrey)",
    linkedTask: "Landing Lumina",
  },
  {
    id: "act-006",
    timestamp: "2026-03-20T21:00:00Z",
    agentId: "reportes",
    agentName: "Reportes",
    agentEmoji: "📊",
    type: "message",
    description: "Generó reporte semanal para cliente Dermacenter — 47 citas recuperadas, ROI +312%",
    linkedTask: "Reporte Semanal - Semana 11",
    toAgentId: "ventas",
    toAgentName: "Ventas",
    toAgentEmoji: "🤝",
  },
  {
    id: "act-007",
    timestamp: "2026-03-20T20:45:00Z",
    agentId: "outreach",
    agentName: "Outreach",
    agentEmoji: "🎯",
    type: "action",
    description: "Identificó 12 nuevos prospectos en Bogotá vía búsqueda en Instagram + Google Maps",
    linkedTask: "Campaña Bogotá-Medellín Q1",
  },
  {
    id: "act-008",
    timestamp: "2026-03-20T20:30:00Z",
    agentId: "ventas",
    agentName: "Ventas",
    agentEmoji: "🤝",
    type: "task",
    description: "Cerró deal con Estética Lumina (Monterrey) — Setup $1,497 + $997/mes. Notificando a Onboarding",
    linkedTask: "Deal Estética Lumina",
    toAgentId: "onboarding",
    toAgentName: "Onboarding",
    toAgentEmoji: "⚙️",
  },
  {
    id: "act-009",
    timestamp: "2026-03-20T20:15:00Z",
    agentId: "onboarding",
    agentName: "Onboarding",
    agentEmoji: "⚙️",
    type: "message",
    description: "Recibió nuevo cliente: Estética Lumina — iniciando checklist de setup (n8n, Supabase, ManyChat)",
    linkedTask: "Setup Estética Lumina",
    toAgentId: "web-builder",
    toAgentName: "Web Builder",
    toAgentEmoji: "🌐",
  },
  {
    id: "act-010",
    timestamp: "2026-03-20T20:00:00Z",
    agentId: "soporte",
    agentName: "Soporte",
    agentEmoji: "🛠️",
    type: "alert",
    description: "Detectó caída de webhook en Clínica Renova (Lima) — resolviendo automáticamente",
    linkedTask: "Ticket #090 - Renova Lima",
  },
  {
    id: "act-011",
    timestamp: "2026-03-20T19:45:00Z",
    agentId: "outreach",
    agentName: "Outreach",
    agentEmoji: "🎯",
    type: "action",
    description: "Envió secuencia de follow-up a 8 prospectos de campaña anterior sin respuesta en 3 días",
    linkedTask: "Follow-up Campaña Feb",
  },
  {
    id: "act-012",
    timestamp: "2026-03-20T19:30:00Z",
    agentId: "reportes",
    agentName: "Reportes",
    agentEmoji: "📊",
    type: "task",
    description: "Actualizó dashboard de métricas — 3 clientes activos, 47 citas recuperadas, $2,991 MRR",
    linkedTask: "Update Dashboard",
  },
  {
    id: "act-013",
    timestamp: "2026-03-20T19:00:00Z",
    agentId: "ventas",
    agentName: "Ventas",
    agentEmoji: "🤝",
    type: "action",
    description: "Envió propuesta comercial personalizada a Clínica Bio Estética (Santiago) — segundo contacto",
    linkedTask: "Propuesta Bio Estética",
  },
  {
    id: "act-014",
    timestamp: "2026-03-20T18:30:00Z",
    agentId: "web-builder",
    agentName: "Web Builder",
    agentEmoji: "🌐",
    type: "task",
    description: "Entregó landing page completa para Dermacenter Buenos Aires — deployed en Vercel",
    linkedTask: "Landing Dermacenter",
  },
  {
    id: "act-015",
    timestamp: "2026-03-20T18:00:00Z",
    agentId: "onboarding",
    agentName: "Onboarding",
    agentEmoji: "⚙️",
    type: "message",
    description: "Setup completado para Clínica Renova (Lima) — todas las integraciones funcionando",
    linkedTask: "Setup Renova Lima",
    toAgentId: "soporte",
    toAgentName: "Soporte",
    toAgentEmoji: "🛠️",
  },
];

export const leads: Lead[] = [
  {
    id: "lead-001",
    clinicName: "Clínica Bella Derma",
    location: "Buenos Aires, Argentina",
    contactName: "Dra. Valentina Rossi",
    email: "valentina@belladerma.com.ar",
    phone: "+54 11 4567-8901",
    stage: "calificado",
    assignedAgent: "ventas",
    lastContact: "hace 8 min",
    notes: "Respondió email en frío. Muy interesada en automatización de WhatsApp. Maneja 80+ citas/mes. Decisión en ~1 semana.",
  },
  {
    id: "lead-002",
    clinicName: "Clínica Bio Estética",
    location: "Santiago, Chile",
    contactName: "Dr. Matías Vargas",
    email: "matias@bioestetica.cl",
    phone: "+56 9 8765 4321",
    stage: "negociacion",
    assignedAgent: "ventas",
    lastContact: "hace 5 horas",
    notes: "Recibió propuesta. Pregunta si pueden personalizar el bot para también agendar por Instagram DM.",
  },
  {
    id: "lead-003",
    clinicName: "Clínica Estética Nova",
    location: "Medellín, Colombia",
    contactName: "Carolina Mejía",
    email: "carolina@esteticanová.com",
    phone: "+57 300 123 4567",
    stage: "contactado",
    assignedAgent: "outreach",
    lastContact: "hace 2 horas",
    notes: "Email enviado hoy. Sin respuesta todavía. Follow-up programado para mañana.",
  },
  {
    id: "lead-004",
    clinicName: "Centro Estético Glow",
    location: "Ciudad de México, México",
    contactName: "Sofía Ramírez",
    email: "sofia@centroglow.mx",
    phone: "+52 55 9876 5432",
    stage: "prospecto",
    assignedAgent: "outreach",
    lastContact: "hace 1 día",
    notes: "Identificada vía Instagram. 12k seguidores, muy activa. Perfil ideal para automatización.",
  },
  {
    id: "lead-005",
    clinicName: "Estética Lumina",
    location: "Monterrey, México",
    contactName: "Dra. Andrea Torres",
    email: "andrea@estlumina.mx",
    phone: "+52 81 1234 5678",
    stage: "cliente",
    assignedAgent: "onboarding",
    lastContact: "hace 30 min",
    notes: "¡CLIENTE CERRADO HOY! Setup $1,497 + $997/mes. Onboarding en progreso. Web Builder construyendo su landing.",
  },
];

export const commandHistory: Command[] = [
  {
    id: "cmd-001",
    timestamp: "2026-03-20T21:00:00Z",
    targetAgent: "outreach",
    command: "Buscar prospectos en Bogotá hoy, enfocarse en clínicas con más de 5k seguidores en Instagram",
    status: "completado",
  },
  {
    id: "cmd-002",
    timestamp: "2026-03-20T20:00:00Z",
    targetAgent: "todos",
    command: "Generar reporte semanal de actividad",
    status: "completado",
  },
  {
    id: "cmd-003",
    timestamp: "2026-03-20T19:00:00Z",
    targetAgent: "ventas",
    command: "Revisar leads fríos de la semana pasada y enviar follow-up personalizado",
    status: "completado",
  },
  {
    id: "cmd-004",
    timestamp: "2026-03-20T18:00:00Z",
    targetAgent: "soporte",
    command: "Verificar que todas las integraciones de clientes activos estén funcionando",
    status: "completado",
  },
];

export const agentMessages: AgentMessage[] = [
  {
    id: "msg-001",
    timestamp: "2026-03-20T21:50:00Z",
    fromAgentId: "outreach",
    fromAgentName: "Outreach",
    fromAgentEmoji: "🎯",
    toAgentId: "ventas",
    toAgentName: "Ventas",
    toAgentEmoji: "🤝",
    message: "Lead calificado: Clínica Bella Derma, CABA, respondió al email. Dra. Valentina Rossi, 80+ citas/mes. Muy interesada. Te la paso.",
  },
  {
    id: "msg-002",
    timestamp: "2026-03-20T20:30:00Z",
    fromAgentId: "ventas",
    fromAgentName: "Ventas",
    fromAgentEmoji: "🤝",
    toAgentId: "onboarding",
    toAgentName: "Onboarding",
    toAgentEmoji: "⚙️",
    message: "Deal cerrado con Estética Lumina (Monterrey). Setup $1,497 + $997/mes. Contacto: Dra. Andrea Torres, andrea@estlumina.mx. Comenzar onboarding ASAP.",
  },
  {
    id: "msg-003",
    timestamp: "2026-03-20T20:15:00Z",
    fromAgentId: "onboarding",
    fromAgentName: "Onboarding",
    fromAgentEmoji: "⚙️",
    toAgentId: "web-builder",
    toAgentName: "Web Builder",
    toAgentEmoji: "🌐",
    message: "Necesito que construyas landing page para Estética Lumina. Referencias: claro, moderno, tonos nude y dorado. URL target: estlumina.mx. Formulario de reservas integrado.",
  },
  {
    id: "msg-004",
    timestamp: "2026-03-20T21:00:00Z",
    fromAgentId: "reportes",
    fromAgentName: "Reportes",
    fromAgentEmoji: "📊",
    toAgentId: "ventas",
    toAgentName: "Ventas",
    toAgentEmoji: "🤝",
    message: "Reporte semanal listo. Dermacenter: 47 citas recuperadas, ROI 312%. Buena prueba social para usar en propuestas. Adjunto el PDF.",
  },
  {
    id: "msg-005",
    timestamp: "2026-03-20T18:00:00Z",
    fromAgentId: "onboarding",
    fromAgentName: "Onboarding",
    fromAgentEmoji: "⚙️",
    toAgentId: "soporte",
    toAgentName: "Soporte",
    toAgentEmoji: "🛠️",
    message: "Setup de Renova Lima completado. Transferiéndoles a tu equipo para monitoreo ongoing. Integraciones: WhatsApp (ManyChat), Google Calendar, Supabase. Todo verde.",
  },
];

export const quickStats = {
  leadsHoy: 12,
  emailsEnviados: 47,
  tareasCompletadas: 23,
  clientesActivos: 3,
};
